import {
  LayoutDashboard,
  // Accessibility,
  UserCircle,
  NotebookPen,
  // Baby,
  // Clock,
  // Receipt,
  Network,
  Calendar,
  Settings,
  Accessibility,
  Users,
} from "lucide-react";
import { all_routes } from "./all_routes";

// export const iconMapping = [
//   {
//     text: "Dashboard",
//     icon: <LayoutDashboard size={20} />,
//     alert: false,
//     active: false,
//     iconText: "Dashboard",
//     to: all_routes.dashboard,
//     table: "dashboard",
//   },
//   // {
//   //   text: "Patients",
//   //   icon: <Accessibility size={20} />,
//   //   alert: true,
//   //   active: false,
//   //   iconText: "Patients",
//   //   to: all_routes.patients,
//   //   table: "patients",
//   // },
//   // {
//   //   text: "Staff",
//   //   icon: <UserCircle size={20} />,
//   //   alert: false,
//   //   active: false,
//   //   iconText: "Staff",
//   //   to: all_routes.staff,
//   //   table: "staff",
//   // },
//   {
//     text: "Users",
//     icon: <UserCircle size={20} />,
//     alert: false,
//     active: false,
//     iconText: "Users",
//     to: all_routes.users,
//     table: "users",
//   },
//   {
//     text: "Patients",
//     icon: <Accessibility size={20} />,
//     alert: true,
//     active: false,
//     iconText: "Patients",
//     to: all_routes.patients,
//     table: "patients",
//   },

//   {
//     text: "Appointments",
//     icon: <NotebookPen size={20} />,
//     alert: true,
//     active: false,
//     iconText: "Appointments",
//     to: all_routes.appointments,
//     table: "appointments",
//   },
//   {
//     text: "Properties",
//     icon: <Settings size={20} />,
//     alert: false,
//     active: false,
//     iconText: "Properties",
//     to: all_routes.properties,
//     table: "properties",
//   },
//   // {
//   //   text: "Pregnancies",
//   //   icon: <Baby size={20} />,
//   //   alert: false,
//   //   active: false,
//   //   iconText: "Pregnancies",
//   //   to: all_routes.pregnancies,
//   //   table: "pregnancies",
//   // },
//   // {
//   //   text: "Labor and Deliveries",
//   //   icon: <Clock size={20} />,
//   //   alert: true,
//   //   active: false,
//   //   iconText: "Labor and Deliveries",
//   //   to: all_routes.laborAndDeliveries,
//   //   table: "labor-and-deliveries",
//   // },
//   // {
//   //   text: "Payments",
//   //   icon: <Receipt size={20} />,
//   //   alert: false,
//   //   active: false,
//   //   iconText: "Payments",
//   //   to: all_routes.payments,
//   //   table: "payments",
//   // },
//   {
//     text: "Org Chart",
//     icon: <Network size={20} />,
//     alert: false,
//     active: false,
//     iconText: "Org Chart",
//     to: all_routes.orgChart,
//     table: "organizational-structure-diagram",
//   },
//   {
//     text: "Calendar",
//     icon: <Calendar size={20} />,
//     alert: false,
//     active: false,
//     iconText: "Calendar",
//     to: all_routes.calendar,
//     table: "calendar",
//   },
// ];

export const iconMapping = [
  {
    section: "Menu",
    items: [
      {
        text: "Dashboard",
        icon: <LayoutDashboard size={20} />,
        alert: false,
        iconText: "Dashboard",
        to: all_routes.dashboard,
        table: "dashboard",
      },

      {
        text: "Calendar",
        icon: <Calendar size={20} />,
        alert: false,
        iconText: "Calendar",
        to: all_routes.calendar,
        table: "calendar",
      },
      {
        text: "Org Chart",
        icon: <Network size={20} />,
        alert: false,
        iconText: "Org Chart",
        to: all_routes.orgChart,
        table: "organizational-structure-diagram",
      },
    ],
  },
  {
    section: "Management",
    items: [
      {
        text: "Doctors",
        icon: <UserCircle size={20} />,
        alert: false,
        iconText: "Doctors",
        to: all_routes.doctors,
        table: "doctors",
      },
      {
        text: "Patients",
        icon: <Users size={20} />,
        alert: false,
        iconText: "Patients",
        to: all_routes.patients,
        table: "patients",
      },
      {
        text: "Appointments",
        icon: <NotebookPen size={20} />,
        alert: false,
        iconText: "Appointments",
        to: all_routes.appointments,
        table: "appointments",
      },
      {
        text: "Inventory",
        icon: <NotebookPen size={20} />,
        alert: false,
        iconText: "Inventory",
        to: all_routes.inventory,
        table: "inventory",
      },
      {
        text: "Inventory Logs",
        icon: <NotebookPen size={20} />,
        alert: false,
        iconText: "Inventory Logs",
        to: all_routes.inventoryLogs,
        table: "inventoryLogs",
      },
    ],
  },
  {
    section: "Settings",
    items: [
      {
        text: "Users",
        icon: <UserCircle size={20} />,
        alert: false,
        iconText: "Users",
        to: all_routes.users,
        table: "users",
      },
      // {
      //   text: "Properties",
      //   icon: <Settings size={20} />,
      //   alert: false,
      //   iconText: "Properties",
      //   to: all_routes.properties,
      //   table: "properties",
      // },
      {
        text: "Settings",
        icon: <Settings size={20} />,
        alert: false,
        iconText: "Settings",
        to: all_routes.settings,
        table: "settings",
      },
      // {
      //   text: "Test Page",
      //   icon: <Settings size={20} />,
      //   alert: false,
      //   iconText: "Test",
      //   to: all_routes.testPage,
      //   table: "test",
      // },
    ],
  },
];
