import {
  LayoutDashboard,
  // Accessibility,
  UserCircle,
  NotebookPen,
  // Baby,
  // Clock,
  // Receipt,
  Network,
  Calendar,
  Settings,
} from "lucide-react";
import { all_routes } from "./all_routes";

export const iconMapping = [
  {
    text: "Dashboard",
    icon: <LayoutDashboard size={20} />,
    alert: false,
    active: false,
    iconText: "Dashboard",
    to: all_routes.dashboard,
    table: "dashboard",
  },
  // {
  //   text: "Patients",
  //   icon: <Accessibility size={20} />,
  //   alert: true,
  //   active: false,
  //   iconText: "Patients",
  //   to: all_routes.patients,
  //   table: "patients",
  // },
  // {
  //   text: "Staff",
  //   icon: <UserCircle size={20} />,
  //   alert: false,
  //   active: false,
  //   iconText: "Staff",
  //   to: all_routes.staff,
  //   table: "staff",
  // },
  {
    text: "Users",
    icon: <UserCircle size={20} />,
    alert: false,
    active: false,
    iconText: "Users",
    to: all_routes.users,
    table: "users",
  },
  {
    text: "Properties",
    icon: <Settings size={20} />,
    alert: false,
    active: false,
    iconText: "Properties",
    to: all_routes.properties,
    table: "properties",
  },
  {
    text: "Appointments",
    icon: <NotebookPen size={20} />,
    alert: true,
    active: false,
    iconText: "Appointments",
    to: all_routes.appointments,
    table: "appointments",
  },
  // {
  //   text: "Pregnancies",
  //   icon: <Baby size={20} />,
  //   alert: false,
  //   active: false,
  //   iconText: "Pregnancies",
  //   to: all_routes.pregnancies,
  //   table: "pregnancies",
  // },
  // {
  //   text: "Labor and Deliveries",
  //   icon: <Clock size={20} />,
  //   alert: true,
  //   active: false,
  //   iconText: "Labor and Deliveries",
  //   to: all_routes.laborAndDeliveries,
  //   table: "labor-and-deliveries",
  // },
  // {
  //   text: "Payments",
  //   icon: <Receipt size={20} />,
  //   alert: false,
  //   active: false,
  //   iconText: "Payments",
  //   to: all_routes.payments,
  //   table: "payments",
  // },
  {
    text: "Org Chart",
    icon: <Network size={20} />,
    alert: false,
    active: false,
    iconText: "Org Chart",
    to: all_routes.orgChart,
    table: "organizational-structure-diagram",
  },
  {
    text: "Calendar",
    icon: <Calendar size={20} />,
    alert: false,
    active: false,
    iconText: "Calendar",
    to: all_routes.calendar,
    table: "calendar",
  },
];
