export const bloodTypeOptions = [
  { label: "A+", value: "A+" },
  { label: "A-", value: "A-" },
  { label: "B+", value: "B+" },
  { label: "B-", value: "B-" },
  { label: "AB+", value: "AB+" },
  { label: "AB-", value: "AB-" },
  { label: "O+", value: "O+" },
  { label: "O-", value: "O-" },
];

// export const doctorSpecializationOptions = [
//   { label: "General Doctor", value: "general_doctor" },
//   { label: "Obstetrician-Gynecologist (OB-GYN)", value: "ob_gyne" },
//   { label: "Pediatrician", value: "pediatrician" },
//   { label: "Cardiologist", value: "cardiologist" },
//   { label: "Dermatologist", value: "dermatologist" },
//   { label: "Neurologist", value: "neurologist" },
//   { label: "Psychiatrist", value: "psychiatrist" },
//   { label: "Surgeon", value: "surgeon" },
//   { label: "Orthopedic Surgeon", value: "orthopedic_surgeon" },
//   { label: "Oncologist", value: "oncologist" },
//   { label: "Endocrinologist", value: "endocrinologist" },
//   { label: "Ophthalmologist", value: "ophthalmologist" },
//   { label: "ENT Specialist", value: "ent_specialist" },
//   { label: "Pulmonologist", value: "pulmonologist" },
//   { label: "Nephrologist", value: "nephrologist" },
//   { label: "Gastroenterologist", value: "gastroenterologist" },
//   { label: "Urologist", value: "urologist" },
//   { label: "Rheumatologist", value: "rheumatologist" },
//   { label: "Hematologist", value: "hematologist" },
//   { label: "Allergist/Immunologist", value: "allergist_immunologist" },
// ];

export const doctorSpecializationOptions = [
  { label: "General Doctor", value: "General Doctor" },
  {
    label: "Obstetrician-Gynecologist (OB-GYN)",
    value: "Obstetrician-Gynecologist (OB-GYN)",
  },
  { label: "Pediatrician", value: "Pediatrician" },
  { label: "Cardiologist", value: "Cardiologist" },
  { label: "Dermatologist", value: "Dermatologist" },
  { label: "Neurologist", value: "Neurologist" },
  { label: "Psychiatrist", value: "Psychiatrist" },
  { label: "Surgeon", value: "Surgeon" },
  { label: "Orthopedic Surgeon", value: "Orthopedic Surgeon" },
  { label: "Oncologist", value: "Oncologist" },
  { label: "Endocrinologist", value: "Endocrinologist" },
  { label: "Ophthalmologist", value: "Ophthalmologist" },
  { label: "ENT Specialist", value: "ENT Specialist" },
  { label: "Pulmonologist", value: "Pulmonologist" },
  { label: "Nephrologist", value: "Nephrologist" },
  { label: "Gastroenterologist", value: "Gastroenterologist" },
  { label: "Urologist", value: "Urologist" },
  { label: "Rheumatologist", value: "Rheumatologist" },
  { label: "Hematologist", value: "Hematologist" },
  { label: "Allergist/Immunologist", value: "Allergist/Immunologist" },
];
